name: bazzora
description: L'alliance parfaite entre Fedora Silverblue, Bazzite et BlueBuild, pour mes besoins.
base-image: ghcr.io/ublue-os/bazzite-gnome
image-version: latest

modules:
  - type: rpm-ostree
    remove:
     - waydroid